server:
  port: 9999

spring:
  application:
    name: smartcampus-service
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://106.13.204.18:5432/db_smart_campus
    url: jdbc:postgresql://101.200.242.67:5432/db_smart_campus
    # username: scs_user
    # password: scs_user
    username: scs_db_user
    password: xzp@7410
  servlet:
       multipart:
           max-request-size: 10MB
           max-file-size: 10MB
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sip.charge.model
  #typeEnumsPackage: com.sip.charge.model.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: MYSQL
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  阿里oss存储服务
oss:
   endpoint: oss-cn-beijing.aliyuncs.com
   bucketUrl: https://scs-image.oss-cn-beijing.aliyuncs.com/
   keyid: aaa # 填写刚刚生成的AccessKey
   keysecret: aa  # 填写刚刚生成的Accesssecret
   bucketname: scs-image # bucket名称
   filehost: user-image    #bucket下文件夹的路径
ykt:
   url: http://120.25.59.199:5088